#!/usr/bin/env python3
"""Tests for the PR export's `## Awaiting an answer` verdict.

What they guard above all is that a human-tailed open thread is listed whatever
else the PR carries — the miss the section exists to make impossible.

Run by path, as `scripts/check-muthur.sh` does.
"""

from __future__ import annotations

import unittest

from gh_export.awaiting import awaiting_section
from gh_export.previous import PreviousExport

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
ME = {"login": "vzakharov"}
URL = "https://github.com/owner/repo/pull/1"


def thread_post(
    cid: int,
    body: str,
    at: str,
    reply_to: int | None = None,
    review_id: int | None = None,
) -> dict:
    return {
        "id": cid,
        "in_reply_to_id": reply_to,
        "pull_request_review_id": review_id,
        "path": "docs/x.md",
        "line": 3,
        "user": ME,
        "created_at": at,
        "body": body,
    }


def comment(cid: int, body: str, at: str) -> dict:
    return {"id": cid, "user": ME, "created_at": at, "body": body}


def review(rid: int, body: str, at: str) -> dict:
    return {"id": rid, "user": ME, "submitted_at": at, "body": body}


def seen(*fragments: str) -> PreviousExport:
    """A committed export carrying each post, as the export renders its link."""
    return PreviousExport("\n".join(f"[{URL}#{f}]({URL}#{f})" for f in fragments), "abc1234")


def section(
    comments=(), reviews=(), review_comments=(), resolved=None, previous=None
) -> str:
    return awaiting_section(
        list(comments),
        list(reviews),
        list(review_comments),
        resolved or {},
        include_resolved=False,
        previous=previous,
    )


class Threads(unittest.TestCase):
    def test_a_human_tail_counts_however_old(self) -> None:
        out = section(
            review_comments=[thread_post(1, "why?", "2026-10-01T00:00:00Z")],
            resolved={1: False},
        )
        self.assertIn("## Awaiting an answer: 1", out)
        self.assertIn("- **T01** `docs/x.md`:3 — unresolved", out)
        self.assertIn("→ [↓](#t01)", out)

    def test_an_agent_tail_is_an_answer_already_given(self) -> None:
        out = section(
            review_comments=[
                thread_post(1, "why?", "2026-10-01T00:00:00Z"),
                thread_post(2, "because" + FOOTER, "2026-10-01T01:00:00Z", reply_to=1),
            ],
            resolved={1: False},
        )
        self.assertIn("## Awaiting an answer: none", out)

    def test_a_human_coming_back_on_an_answer_counts(self) -> None:
        out = section(
            review_comments=[
                thread_post(1, "why?", "2026-10-01T00:00:00Z"),
                thread_post(2, "because" + FOOTER, "2026-10-01T01:00:00Z", reply_to=1),
                thread_post(3, "not convinced", "2026-10-01T02:00:00Z", reply_to=1),
            ],
            resolved={1: False},
        )
        self.assertIn('"not convinced"', out)

    def test_a_follow_up_submitted_after_the_answer_counts(self) -> None:
        # Written into a pending review before the agent replied, submitted
        # after: its `created_at` is older than the reply it comes back on.
        out = section(
            review_comments=[
                thread_post(1, "why?", "2026-10-01T00:00:00Z"),
                thread_post(3, "not convinced", "2026-10-01T01:30:00Z", 1, review_id=9),
                thread_post(2, "because" + FOOTER, "2026-10-01T02:00:00Z", reply_to=1),
            ],
            reviews=[{"id": 9, "user": ME, "submitted_at": "2026-10-01T03:00:00Z", "body": ""}],
            resolved={1: False},
        )
        self.assertIn('"not convinced"', out)

    def test_a_resolved_thread_never_counts(self) -> None:
        out = section(
            review_comments=[thread_post(1, "why?", "2026-10-07T00:00:00Z")],
            resolved={1: True},
        )
        self.assertIn("## Awaiting an answer: none", out)

    def test_numbering_skips_what_the_export_drops(self) -> None:
        # T<nn> must match the index row below, which numbers only kept threads.
        out = section(
            review_comments=[
                thread_post(1, "closed", "2026-10-01T00:00:00Z"),
                thread_post(2, "open", "2026-10-02T00:00:00Z"),
            ],
            resolved={1: True, 2: False},
        )
        self.assertIn("- **T01** `docs/x.md`:3 — unresolved", out)
        self.assertIn("(#t01)", out)


AGENT_LATER = comment(99, "on another thread" + FOOTER, "2026-10-06T10:06:00Z")


class Novelty(unittest.TestCase):
    def test_an_unseen_comment_counts_whatever_the_agent_posted_since(self) -> None:
        # The agent's later post answers something else; it never saw this one.
        out = section(
            comments=[comment(1, "rename Y", "2026-10-06T10:05:00Z"), AGENT_LATER],
            previous=seen("issuecomment-99"),
        )
        self.assertIn("- **C01** @vzakharov (human)", out)
        self.assertIn("(#c01)", out)

    def test_a_seen_comment_an_agent_post_followed_does_not(self) -> None:
        out = section(
            comments=[comment(1, "rename Y", "2026-10-06T10:05:00Z"), AGENT_LATER],
            previous=seen("issuecomment-1"),
        )
        self.assertIn("## Awaiting an answer: none", out)

    def test_a_seen_comment_with_nothing_from_the_agent_since_counts(self) -> None:
        # Read, committed, then the context was lost before any answer.
        out = section(
            comments=[comment(1, "rename Y", "2026-10-06T10:05:00Z")],
            previous=seen("issuecomment-1"),
        )
        self.assertIn("## Awaiting an answer: 1", out)

    def test_an_inline_reply_counts_as_an_agent_post(self) -> None:
        out = section(
            comments=[comment(1, "rename Y", "2026-10-06T10:05:00Z")],
            review_comments=[
                thread_post(5, "x?", "2026-10-06T09:00:00Z"),
                thread_post(6, "x." + FOOTER, "2026-10-06T10:06:00Z", reply_to=5),
            ],
            resolved={5: False},
            previous=seen("issuecomment-1"),
        )
        self.assertIn("## Awaiting an answer: none", out)

    def test_the_agents_own_sticky_comments_never_count(self) -> None:
        out = section(comments=[comment(1, "Proposed squash" + FOOTER, "2026-10-06T09:00:00Z")])
        self.assertIn("## Awaiting an answer: none", out)

    def test_an_unseen_review_body_counts(self) -> None:
        out = section(
            reviews=[
                review(7, "", "2026-10-06T09:00:00Z"),
                review(8, "see inline", "2026-10-06T09:00:00Z"),
            ],
            comments=[AGENT_LATER],
            previous=seen("pullrequestreview-7"),
        )
        # The bodiless review renders nothing, so `R01` is the bodied one.
        self.assertIn("- **R01** review by @vzakharov (human)", out)
        self.assertIn("(#r01)", out)

    def test_with_no_export_only_an_agent_post_settles_a_post(self) -> None:
        answered = section(
            comments=[comment(1, "old", "2026-10-06T10:05:00Z"), AGENT_LATER]
        )
        self.assertIn("## Awaiting an answer: none", answered)
        self.assertIn("no export committed on the branch yet", answered)
        waiting = section(comments=[comment(1, "old", "2026-10-06T10:05:00Z")])
        self.assertIn("## Awaiting an answer: 1", waiting)

    def test_the_rule_names_the_export_it_read(self) -> None:
        self.assertIn("the export committed at abc1234", section(previous=seen()))


if __name__ == "__main__":
    unittest.main()
