#!/usr/bin/env python3
"""Tests for the PR export's `## Awaiting an answer` verdict.

What they guard above all is that a human-tailed open thread is listed whatever
else the PR carries — the miss the section exists to make impossible.

Run by path, as `scripts/check-muthur.sh` does.
"""

from __future__ import annotations

import unittest

from gh_export.awaiting import awaiting_section

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
HEAD_SHA = "83a2868aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
PR = {"head": {"sha": HEAD_SHA}}
TIMELINE = [
    {"event": "committed", "sha": "0000000", "committer": {"date": "2026-10-06T07:00:00Z"}},
    {"event": "committed", "sha": HEAD_SHA, "committer": {"date": "2026-10-06T08:00:00Z"}},
]
ME = {"login": "vzakharov"}


def thread_post(
    cid: int,
    body: str,
    at: str,
    reply_to: int | None = None,
    review_id: int | None = None,
) -> dict:
    return {
        "id": cid,
        "in_reply_to_id": reply_to,
        "pull_request_review_id": review_id,
        "path": "docs/x.md",
        "line": 3,
        "user": ME,
        "created_at": at,
        "body": body,
    }


def post(body: str, at: str, stamp: str = "created_at") -> dict:
    return {"user": ME, stamp: at, "body": body}


def section(
    comments=(), reviews=(), review_comments=(), resolved=None, timeline=TIMELINE
) -> str:
    return awaiting_section(
        PR,
        list(timeline),
        list(comments),
        list(reviews),
        list(review_comments),
        resolved or {},
        include_resolved=False,
    )


class Threads(unittest.TestCase):
    def test_a_human_tail_counts_however_old(self) -> None:
        out = section(
            review_comments=[thread_post(1, "why?", "2026-10-01T00:00:00Z")],
            resolved={1: False},
        )
        self.assertIn("## Awaiting an answer: 1", out)
        self.assertIn("- **T01** `docs/x.md`:3 — unresolved", out)
        self.assertIn("→ [↓](#t01)", out)

    def test_an_agent_tail_is_an_answer_already_given(self) -> None:
        out = section(
            review_comments=[
                thread_post(1, "why?", "2026-10-01T00:00:00Z"),
                thread_post(2, "because" + FOOTER, "2026-10-01T01:00:00Z", reply_to=1),
            ],
            resolved={1: False},
        )
        self.assertIn("## Awaiting an answer: none", out)

    def test_a_human_coming_back_on_an_answer_counts(self) -> None:
        out = section(
            review_comments=[
                thread_post(1, "why?", "2026-10-01T00:00:00Z"),
                thread_post(2, "because" + FOOTER, "2026-10-01T01:00:00Z", reply_to=1),
                thread_post(3, "not convinced", "2026-10-01T02:00:00Z", reply_to=1),
            ],
            resolved={1: False},
        )
        self.assertIn('"not convinced"', out)

    def test_a_follow_up_submitted_after_the_answer_counts(self) -> None:
        # Written into a pending review before the agent replied, submitted
        # after: its `created_at` is older than the reply it comes back on.
        out = section(
            review_comments=[
                thread_post(1, "why?", "2026-10-01T00:00:00Z"),
                thread_post(3, "not convinced", "2026-10-01T01:30:00Z", 1, review_id=9),
                thread_post(2, "because" + FOOTER, "2026-10-01T02:00:00Z", reply_to=1),
            ],
            reviews=[{"id": 9, "user": ME, "submitted_at": "2026-10-01T03:00:00Z", "body": ""}],
            resolved={1: False},
        )
        self.assertIn('"not convinced"', out)

    def test_a_resolved_thread_never_counts(self) -> None:
        out = section(
            review_comments=[thread_post(1, "why?", "2026-10-07T00:00:00Z")],
            resolved={1: True},
        )
        self.assertIn("## Awaiting an answer: none", out)

    def test_numbering_skips_what_the_export_drops(self) -> None:
        # T<nn> must match the index row below, which numbers only kept threads.
        out = section(
            review_comments=[
                thread_post(1, "closed", "2026-10-01T00:00:00Z"),
                thread_post(2, "open", "2026-10-02T00:00:00Z"),
            ],
            resolved={1: True, 2: False},
        )
        self.assertIn("- **T01** `docs/x.md`:3 — unresolved", out)
        self.assertIn("(#t01)", out)


class Recency(unittest.TestCase):
    def test_a_human_comment_after_the_head_commit_counts(self) -> None:
        out = section(comments=[post("ping", "2026-10-06T09:00:00Z")])
        self.assertIn("- **C01** @vzakharov (human)", out)
        self.assertIn("(#c01)", out)

    def test_a_comment_before_the_head_commit_does_not(self) -> None:
        out = section(comments=[post("old", "2026-10-06T07:30:00Z")])
        self.assertIn("## Awaiting an answer: none", out)

    def test_the_agents_own_sticky_comments_never_count(self) -> None:
        out = section(comments=[post("Proposed squash" + FOOTER, "2026-10-06T09:00:00Z")])
        self.assertIn("## Awaiting an answer: none", out)

    def test_a_review_body_after_the_head_commit_counts(self) -> None:
        out = section(
            reviews=[
                post("", "2026-10-06T09:00:00Z", "submitted_at"),
                post("see inline", "2026-10-06T09:00:00Z", "submitted_at"),
            ]
        )
        # The bodiless review renders nothing, so `R01` is the bodied one.
        self.assertIn("- **R01** review by @vzakharov (human)", out)
        self.assertIn("(#r01)", out)

    def test_no_head_date_counts_every_human_post(self) -> None:
        out = section(comments=[post("old", "2026-01-01T00:00:00Z")], timeline=[])
        self.assertIn("## Awaiting an answer: 1", out)
        self.assertIn("83a2868, date not on the timeline", out)

    def test_the_rule_names_the_head_commit(self) -> None:
        self.assertIn("(83a2868, 2026-10-06T08:00:00Z)", section())


if __name__ == "__main__":
    unittest.main()
